Option to change Context options
Metatavu/essote-management-portal pull request #163
Opened 2022-09-21 08:20 UTC by btepu002xamk

User can change context options

2022-09-21 10:08 UTC, villejuutila reviewed
Added comments

2022-09-21 10:08 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +  const [ contextManagementListOption, setContextManagementListOption ] = React.useState<boolean>(false);
```suggestion
  const [ contextOption, setContextOption ] = useState<FormContext[]>( [FormContext.FORM, FormContext.MANAGEMENT ]);
```

2022-09-21 10:08 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
>    /**
```suggestion
  const renderContextOptions = () => (
      <>
        <Divider/>
        <Typography variant="subtitle1">{ strings.draftEditorScreen.editor.features.ContextVisibilityInfo }</Typography>
        <FormControl>
          <FormControlLabel
            label={ strings.draftEditorScreen.editor.features.contextFormVisibility }
            control={
              <Checkbox
                checked={ contextFormOption }
                onChange={ event => updateContexts("FORM", event.target.checked) }
              />
            }
          />
        </FormControl>
        <FormControl>
          <FormControlLabel
            label={ strings.draftEditorScreen.editor.features.contextManagementVisibility }
            control={
              <Checkbox
                checked={ contextManagementOption }
                onChange={ event => updateContexts("MANAGEMENT", event.target.checked) }
              />
            }
          />
        </FormControl>
        <FormControl>
          <FormControlLabel
            label={ strings.draftEditorScreen.editor.features.contextManagementListVisibility }
            control={
              <Checkbox
                checked={ contextManagementListOption }
                onChange={ event => updateContexts("MANAGEMENT_LIST", event.target.checked) }
              />
            }
          />
        </FormControl>
      </>
    );
  );
  
  /**
```

2022-09-21 10:08 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
>    /**
```suggestion
  const renderContextOptions = () => (
      <>
        <Divider/>
        <Typography variant="subtitle1">{ strings.draftEditorScreen.editor.features.ContextVisibilityInfo }</Typography>
        <FormControl>
          <FormControlLabel
            label={ strings.draftEditorScreen.editor.features.contextFormVisibility }
            control={
              <Checkbox
                checked={ contextFormOption }
                onChange={ event => updateContexts("FORM", event.target.checked) }
              />
            }
          />
        </FormControl>
        <FormControl>
          <FormControlLabel
            label={ strings.draftEditorScreen.editor.features.contextManagementVisibility }
            control={
              <Checkbox
                checked={ contextManagementOption }
                onChange={ event => updateContexts("MANAGEMENT", event.target.checked) }
              />
            }
          />
        </FormControl>
        <FormControl>
          <FormControlLabel
            label={ strings.draftEditorScreen.editor.features.contextManagementListVisibility }
            control={
              <Checkbox
                checked={ contextManagementListOption }
                onChange={ event => updateContexts("MANAGEMENT_LIST", event.target.checked) }
              />
            }
          />
        </FormControl>
      </>
    );
  );
  
  /**
```

2022-09-21 10:08 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +    return (
```suggestion
  const renderContextOptions = () => (
```

2022-09-21 10:08 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
>    /**
```suggestion
  );
  
  /**
```

2022-09-21 10:08 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +                checked={ contextFormOption }
```suggestion
                checked={ contextOption.includes(FormContext.FORM) }
```

2022-09-21 10:08 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +                checked={ contextManagementOption }
```suggestion
                checked={ contextOption.includes(FormContext.MANAGEMENT) }
```

2022-09-21 10:08 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +                checked={ contextManagementListOption }
```suggestion
                checked={ contextOption.includes(FormContext.MANAGEMENT_LIST) }
```

2022-09-26 05:39 UTC, villejuutila requested changes
Added comments

2022-09-26 05:39 UTC, villejuutila commented on src/types/index.ts
> + * Enum for different types of Contexts
```suggestion
 * Enum for different types of Contexts for form fields
```

2022-09-26 05:39 UTC, villejuutila commented on src/localization/fi.json
> +        "contextManagementListVisibility":"Näkyy hallinnointilista näkymässä",
```suggestion
        "contextManagementListVisibility":"Näkyy hallinnointi listaus näkymässä",
```

2022-09-26 05:39 UTC, villejuutila commented on src/localization/fi.json
> +        "contextFormVisibility":"Näkyy lomakkeella täyttäessä",
```suggestion
        "contextFormVisibility":"Näkyy lomaketta täyttäessä",
```

2022-09-26 05:39 UTC, villejuutila commented on src/localization/en.json
> +        "contextManagementListVisibility":"Shown on managementlist screen",
```suggestion
        "contextManagementListVisibility":"Shown on management list screen",
```

2022-09-26 05:39 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +    }
Move this conditional check into _checkContextSettings()_ method and only call the method itself from useEffect.

2022-09-26 05:39 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +  const [ contextOption, setContextOption ] = useState<FormContext[]>([FormContext.FORM, FormContext.MANAGEMENT]);
```suggestion
  const [ contextOption, setContextOption ] = useState<FormContext[]>([]);
```

2022-09-26 05:39 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +    }
Move `if (checked)` into else branch of `if (!checked)`

2022-09-26 05:39 UTC, villejuutila commented on src/utils/metaform-utils.ts
> +          contexts: ["FORM", "MANAGEMENT"],
```suggestion
          contexts: [ FormContext.FORM, FormContext.MANAGEMENT ]
```
Use FormContext enum values instead.
Do the same thing for all cases in this switch.

2022-09-27 07:23 UTC, villejuutila requested changes
Added comments

2022-09-27 07:23 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +  const updateContexts = (selectedContext: string, checked: boolean) => {
```suggestion
  const updateContexts = (selectedContext: FormContext, checked: boolean) => {
```

2022-09-27 07:23 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +          return null;
Isn't this return redundant? Change .map to .forEach

2022-09-27 07:23 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +        return null;
Isn't this return redundant? Change .map to .forEach

2022-09-27 07:23 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +   * When changing field check what context settings field have
```suggestion
   * Checks fields contexts
```

2022-09-27 07:23 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +    <>
```suggestion
    <Stack spacing={ 2 }>
```

2022-09-27 07:23 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +    </>
```suggestion
    </Stack>
```

2022-09-27 07:23 UTC, villejuutila commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +          return null;
```suggestion
          break;
```

2022-09-27 07:23 UTC, villejuutila commented on src/localization/fi.json
> +        "contextManagementListVisibility":"Näkyy hallinnointilista näkymässä",
```suggestion
        "contextManagementListVisibility":"Näkyy hallinnoin listaus näkymässä",
```

2022-09-27 07:23 UTC, villejuutila commented on src/localization/fi.json
> +        "ContextVisibilityInfo":"Kentän hallinnointi asetukset"
```suggestion
        "contextVisibilityInfo": "Kentän hallinnointi asetukset"
```

2022-09-27 07:23 UTC, villejuutila commented on src/localization/fi.json
> +        "addCustomHtml":"Lisää tähän HTML-sisältöä",
```suggestion
        "addCustomHtml": "Lisää tähän HTML-sisältöä",
```

2022-09-27 07:23 UTC, villejuutila commented on src/localization/fi.json
> +        "contextFormVisibility":"Näkyy lomaketta täyttäessä",
```suggestion
        "contextFormVisibility": "Näkyy lomaketta täyttäessä",
```

2022-09-27 07:23 UTC, villejuutila commented on src/localization/fi.json
> +        "contextManagementVisibility":"Näkyy hallinnointi näkymässä",
```suggestion
        "contextManagementVisibility": "Näkyy hallinnointi näkymässä",
```

2022-09-27 07:23 UTC, villejuutila commented on src/localization/fi.json
> +        "contextManagementListVisibility":"Näkyy hallinnointilista näkymässä",
```suggestion
        "contextManagementListVisibility": "Näkyy hallinnointilista näkymässä",
```

2022-09-27 07:23 UTC, villejuutila commented on src/types/index.ts
> + * Enum for different types of Contexts for form fields
```suggestion
 * Enum for MetaformField context values
```

2022-09-27 09:40 UTC, Chi-Chu319 approved these changes

2022-09-27 09:40 UTC, Chi-Chu319 commented on src/components/editor/metaform-editor-right-drawer-feature.tsx
> +        }
Whats the point since they are all the same operation

2022-09-27 13:01 UTC, villejuutila approved these changes
Approved

2022-09-28 08:58 UTC, merged