User can change form visibility
Metatavu/essote-management-portal pull request #184
Opened 2022-09-30 08:01 UTC by btepu002xamk

As user i would like to change visibility of form.

2022-09-30 11:50 UTC, Chi-Chu319 requested changes

2022-09-30 11:50 UTC, Chi-Chu319 commented on src/components/editor/metaform-editor-left-drawer.tsx
> +      <Divider sx={{ mt: "10px", mb: "5px" }}/>
instead of using margin, wrap the form with stack and set spacing

2022-09-30 11:50 UTC, Chi-Chu319 commented on src/components/editor/metaform-editor-left-drawer.tsx
> +          </Select>
```suggestion
          <Textfield
            select
           label={ strings.draftEditorScreen.editor.visibility.metaformVisibilityLabel }
            value={ pendingForm?.visibility }
            onChange={ event => onFormVisibilityChange(event.target.value as MetaformVisibility) }
          >
            <MenuItem value={ VisibilityOptions.PUBLIC }>{ strings.draftEditorScreen.editor.visibility.public }</MenuItem>
            <MenuItem value={ VisibilityOptions.PRIVATE }>{ strings.draftEditorScreen.editor.visibility.private }</MenuItem>
          </Textfield>
```

2022-10-03 05:58 UTC, villejuutila requested changes
Added comments

2022-10-03 05:58 UTC, villejuutila commented on src/components/editor/metaform-editor-left-drawer.tsx
> +      <FormControl fullWidth>
You should wrap the entire component inside <FormControl> and probably <Stack>

2022-10-03 05:58 UTC, villejuutila commented on src/components/editor/metaform-editor-left-drawer.tsx
> +            <MenuItem value={ VisibilityOptions.PRIVATE }>{ strings.draftEditorScreen.editor.visibility.private }</MenuItem>
Why not use the generated type MetaformVisibility?

2022-10-03 05:58 UTC, villejuutila commented on src/types/index.ts
> +
Why not use the generated type MetaformVisibility?

2022-10-03 05:58 UTC, villejuutila commented on src/localization/en.json
> +        "metaformVisibilityLabel": "Form is",
Would it be more in line with the theme to just have "Visibility" or "Form visibility" as label?

2022-10-03 05:58 UTC, villejuutila commented on src/localization/fi.json
> +        "metaformVisibilityLabel": "Lomake on",
Would it be more in line with the theme to just have "Visibility" or "Form visibility" as label?

2022-10-03 07:39 UTC, villejuutila approved these changes

2022-10-05 09:19 UTC, Chi-Chu319 approved these changes

2022-10-05 17:45 UTC, closed without merging